apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: rambooreddy/nginx-web1:v1 
        ports:
        - containerPort: 8080