name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nginx-web1:${{ steps.generate_build_number.outputs.build_number }}
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
    - name: Push the Docker image
      run: docker push "${{ secrets.DOCKER_HUB_USERNAME }}"/nginx-web1:${{ steps.generate_build_number.outputs.build_number }}