name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        sudo echo  testing the version number v1
        sudo docker build . --file Dockerfile --tag nginx-web1:v1
    - name: Login to Docker Hub
      run: sudo echo "${{ secrets.DOCKER_HUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
    - name: listing the Docker image
      run: sudo docker images -a
    - name: tagging the docker image name with respect to docker hub username
      run: sudo docker tag nginx-web1:v1 "${{ secrets.DOCKER_HUB_USERNAME }}"/nginx-web1:v1
    - name: Docker image name after tagging
      run: sudo docker images -a
    - name: Push the Docker image
      run: sudo docker push "${{ secrets.DOCKER_HUB_USERNAME }}"/nginx-web1:v1